compute_environment: LOCAL_MACHINE
distributed_type: DEEPSPEED
mixed_precision: bf16

deepspeed_config:
  zero_stage: 2
  train_micro_batch_size_per_gpu: 4
  contiguous_gradients: true
  overlap_comm: true
  reduce_scatter: true
  reduce_bucket_size: 2e8
  allgather_bucket_size: 2e8
  offload_optimizer_device: none
  offload_param_device: none

num_processes: 2
machine_rank: 0
main_process_ip: null
main_process_port: null
main_training_function: main